#!/usr/bin/env python
# Query the status of pwrstat and send certain info
# to Zabbix
#
# The is no error checking in this script!

# # Config # #

# How often to poll the UPS and report status in seconds.
poll_interval = 15

# The host running the zabbix-server.
zabbix_server = '192.168.0.100'

# The name of the Zabbix host being monitored.
zabbix_host = 'ups1'

# The keys we are reporting on and how to find the data.
zabbix_keys = {'State........................': 'ups.status',
               'Battery Capacity.............': 'ups.battery.level',
               'Load.........................': 'ups.load',
               'Remaining Runtime............': 'ups.runtime',
               'Power Supply by..............': 'ups.supplier'}

# # Script # #

import subprocess
import time

while True:
    try:
        print "Getting status"
        status = subprocess.Popen(['pwrstat', '-status'], stdout=subprocess.PIPE).communicate()[0]
        print status
    except subprocess.CalledProcessError:
        print "Got a non-zero return code"
        
        
    for line in status.splitlines():
        line = line.lstrip()
        if len(line) > 29:
            key = line[:29]
            if zabbix_keys.has_key(key): 
                print "Stat: %s" % key
                line = line[30:]
                value = line.split()[0]
                print "Value: %s" % value
            
                zabbix_key = zabbix_keys.get(key)
                # Report status back.
                print "Reporting stat: %s: %s" % (zabbix_key, value)
                subprocess.call(['zabbix_sender', '-z', zabbix_server, '-s', zabbix_host, '-k', zabbix_key, '-o', value])
  

    # Sleep until next time.
    time.sleep(poll_interval)

