#!/usr/bin/env python
# Query the status of pwrstat and send certain info
# to Zabbix
#
# The is no error checking in this script!

# # Config # #

# How often to poll the UPS and report status in seconds.
poll_interval = 15

# The host running the zabbix-server.
zabbix_server = '192.168.0.100'

# The name of the Zabbix host being monitored.
zabbix_host = 'ups1'

# The keys we are reporting on and how to find the data.
zabbix_keys = {'State........................': 'ups.status',
               'Battery Capacity.............': 'ups.battery.level',
               'Load.........................': 'ups.load',
               'Remaining Runtime............': 'ups.runtime',
               'Power Supply by..............': 'ups.supplier'}

# # Script # #

import logging
import logging.handlers
import os
import subprocess
import time

# Setup the logger
logger = logging.getLogger('upsWatcher')
logger.setLevel(logging.DEBUG)

logfile = "upsWatcher.log"
# Determine the logger location
if not os.path.exists(os.path.join(os.getcwd(), 'setup.py')):
    # We are in production.
    logfile = os.path.join("var", "log", logfile)

# Add the log message handler to the logger
file_handler = logging.handlers.RotatingFileHandler(
               logfile, maxBytes=10240, backupCount=7)
file_handler.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
file_handler.setFormatter(formatter)

logger.addHandler(file_handler)

while True:
    try:
        logger.debug("Getting status")
        status = subprocess.Popen(['pwrstat', '-status'], stdout=subprocess.PIPE).communicate()[0]
        logger.debug(status)
    except subprocess.CalledProcessError:
        logger.warn("Got a non-zero return code when running pwrstat")
        
        
    for line in status.splitlines():
        line = line.lstrip()
        if len(line) > 29:
            key = line[:29]
            if zabbix_keys.has_key(key): 
                logger.debug("Stat: %s" % key)
                line = line[30:]
                value = line.split()[0]
                logger.debug("Value: %s" % value)
            
                zabbix_key = zabbix_keys.get(key)
                # Report status back.
                logger.info("Reporting stat: %s: %s" % (zabbix_key, value))
                subprocess.call(['zabbix_sender', '-z', zabbix_server, '-s', zabbix_host, '-k', zabbix_key, '-o', value])
  

    # Sleep until next time.
    time.sleep(poll_interval)

